#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countingValleys function below.
def countingValleys(n, s):
    count=0
    sl=0
    for i in s:
        if i =='U':
            count=count+1
        else:
            count=count-1  
        if count==0 and i is 'U':
            sl=sl+1
            print(sl)
    return(sl)
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    s = input()

    result = countingValleys(n, s)

    fptr.write(str(result) + '\n')

    fptr.close()
